//go:build kubernetes

package controlplane

import (
	"context"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/posthog/duckgres/controlplane/admin"
	"github.com/posthog/duckgres/controlplane/configstore"
	"github.com/posthog/duckgres/controlplane/provisioner"
	"github.com/posthog/duckgres/controlplane/provisioner/opa"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
)

// newTrinoKubeClient builds an in-cluster typed kubernetes.Interface for
// the Trino provisioner's Secret + ConfigMap projections. Returns the
// in-cluster client error verbatim so the caller can log+skip rather
// than fatal-out a non-K8s deployment.
func newTrinoKubeClient() (kubernetes.Interface, error) {
	cfg, err := rest.InClusterConfig()
	if err != nil {
		return nil, fmt.Errorf("in-cluster config: %w", err)
	}
	kc, err := kubernetes.NewForConfig(cfg)
	if err != nil {
		return nil, fmt.Errorf("kubernetes client: %w", err)
	}
	return kc, nil
}

// Env-only knobs that wire the Trino provisioner branch.
//
// Intent inference (no explicit on/off gate):
//
//	Enablement is signaled by setting DUCKGRES_TRINO_COORDINATOR_URL.
//	If the URL is empty, the provisioner branch is off and existing
//	non-MW deployments stay unaffected. If the URL is set, the other
//	required env vars must also be set; missing-required-value errors
//	are fatal at startup (silently no-op'ing wouldn't help — the chart
//	side would be waiting forever for projections that never come).
//
// Credentials are NOT env vars:
//
//	The Trino node-to-node shared secret, the admin password+hash, and
//	the OPA bundle bearer token are self-generated by the provisioner
//	(ensureClusterSecrets) on first startup, with the K8s Secret as the
//	source of truth. The PER-TENANT metadata-store passwords aren't env
//	vars either — they're read from each org's Duckling CR on every
//	reconcile tick and projected into one Secret.
const (
	// envTrinoCoordinatorURL is the Trino coordinator's REST endpoint,
	// e.g. https://trino-coordinator.trino-customer.svc:8443. Setting
	// this to a non-empty value enables the Trino provisioner branch;
	// leaving it empty disables it. Required configuration when enabled.
	//
	// One cell today, so one URL. See resolveTrinoCell for the shape a
	// second cell takes.
	envTrinoCoordinatorURL = "DUCKGRES_TRINO_COORDINATOR_URL"

	// envTrinoCoordinatorServerName is the TLS server name (the coordinator
	// cert's CN/SAN, e.g. trino.dw.dev.postwh.com) to verify against when
	// DUCKGRES_TRINO_COORDINATOR_URL is https. The provisioner dials the
	// in-cluster Service address, but cert-manager issues the coordinator cert
	// for the external hostname, which doesn't match; setting this keeps full
	// TLS verification (chain + this name) without InsecureSkipVerify. Empty =
	// verify against the URL host (correct if the URL already uses the cert
	// hostname). Ignored for http URLs. Trino rejects password auth over plain
	// http, so https is effectively required for the provisioner to authenticate.
	envTrinoCoordinatorServerName = "DUCKGRES_TRINO_COORDINATOR_SERVER_NAME"

	// envTrinoClientURL is the HTTPS endpoint tenant clients should dial.
	// Empty falls back to the coordinator URL, with its TLS server name used
	// as the host when configured.
	envTrinoClientURL = "DUCKGRES_TRINO_CLIENT_URL"

	// envTrinoCellID names the Trino cell this control plane reconciles.
	// Empty == configstore.DefaultTrinoCellID. The provisioner claims
	// unassigned Trino-enabled orgs into this cell and ignores orgs
	// stamped with any other cell, so two control planes pointed at two
	// coordinators MUST carry different values here — sharing one would
	// have both fight over every tenant's projections.
	envTrinoCellID = "DUCKGRES_TRINO_CELL_ID"

	// envTrinoAWSRegion is the FALLBACK region for a per-org catalog whose
	// warehouse row carries no s3_region. The row is authoritative.
	envTrinoAWSRegion = "DUCKGRES_TRINO_AWS_REGION"

	// envTrinoNamespace overrides provisioner.TrinoCustomerNamespace
	// for the projected Secrets + ConfigMap. Empty = default
	// ("trino-customer"). Useful for dev clusters that namespace
	// Trino differently.
	envTrinoNamespace = "DUCKGRES_TRINO_NAMESPACE"

	// envTrinoTenantSecretMountPath overrides where the chart mounts the
	// tenant-password Secret inside the Trino pods. It is rendered into
	// every catalog's ducklake.metadata.connection-password-file, so it
	// MUST match the chart's volumeMount; a mismatch makes every catalog
	// fail to open a metadata connection. Empty ==
	// provisioner.DefaultTrinoTenantSecretMountPath.
	envTrinoTenantSecretMountPath = "DUCKGRES_TRINO_TENANT_SECRET_MOUNT_PATH" //nolint:gosec // env var name, not a credential

	// envTrinoS3MaxConnections overrides the per-catalog S3 connection
	// pool bound. Empty or unparseable == the provisioner default.
	envTrinoS3MaxConnections = "DUCKGRES_TRINO_S3_MAX_CONNECTIONS"
)

// trinoProvisionerEnabled reports whether the control plane should
// wire the Trino provisioner branch. True iff
// DUCKGRES_TRINO_COORDINATOR_URL is non-empty; the URL doubles as the
// enable signal because operators can't meaningfully use the
// provisioner without it (there'd be nothing to talk to).
func trinoProvisionerEnabled() bool {
	return strings.TrimSpace(os.Getenv(envTrinoCoordinatorURL)) != ""
}

// trinoCell is one Trino cell: an id plus the coordinator that serves it.
// A cell is the unit a shared Trino deployment scales in — one coordinator
// and worker fleet, one OPA sidecar, one set of projected Secrets, and the
// orgs stamped with its id.
//
// There is exactly ONE cell today, described by the two env vars below.
// The shape a second cell takes is deliberate and small: resolveTrinoCell
// becomes resolveTrinoCells returning a map[cellID]trinoCell (parsed from a
// JSON env var or a mounted config), SetupMultiTenant builds one
// TrinoProvisioner per entry, and each provisioner keeps reconciling only
// the orgs its own claim/skip filter admits. Nothing else in the reconcile
// path has to change — which is the entire reason the cell id is on the row
// rather than implied by the deployment.
//
// What is explicitly NOT here and NOT planned in this change: assignment
// policy (which cell should a new org land on?), capacity accounting,
// rebalancing, or draining a cell. An org lands on whichever cell claims it
// first, and today only one does.
type trinoCell struct {
	ID             string
	CoordinatorURL string
	TLSServerName  string
	ClientURL      string
}

// resolveTrinoCell reads the single cell's configuration from the
// environment. Returns an error when the coordinator URL is missing, which
// is fatal for an operator who asked for Trino.
func resolveTrinoCell() (trinoCell, error) {
	coordinatorURL := strings.TrimSpace(os.Getenv(envTrinoCoordinatorURL))
	if coordinatorURL == "" {
		return trinoCell{}, fmt.Errorf("%s is required to enable the Trino provisioner branch", envTrinoCoordinatorURL)
	}
	cellID := strings.TrimSpace(os.Getenv(envTrinoCellID))
	if cellID == "" {
		cellID = configstore.DefaultTrinoCellID
	}
	return trinoCell{
		ID:             cellID,
		CoordinatorURL: coordinatorURL,
		TLSServerName:  strings.TrimSpace(os.Getenv(envTrinoCoordinatorServerName)),
		ClientURL:      strings.TrimSpace(os.Getenv(envTrinoClientURL)),
	}, nil
}

// trinoWiring carries the runtime objects multitenant.go has to mount
// onto the provisioning controller + the API server when the Trino
// branch is enabled. Returned together so the caller doesn't have to
// re-derive any of them.
type trinoWiring struct {
	Provisioner *provisioner.TrinoProvisioner
	BundleStore *opa.BundleStore
	// BundleHandler is the HTTP handler the API server mounts for the
	// cell's OPA sidecar's bundle plugin to poll. Authenticated with the
	// bundle bearer token, which is generated once at cluster bootstrap
	// and stable for the process lifetime (rotation is a follow-up
	// rotation-API concern).
	BundleHandler *opa.Handler
	// Cell is the cell this wiring reconciles; carried out for startup
	// logging.
	Cell trinoCell
	// Console is what the admin console needs to observe this cell. Built
	// here rather than in multitenant.go so the observer credential is read
	// through the provisioner that owns it and nothing else has to know how
	// the coordinator is authenticated.
	Console *trinoConsoleWiring
}

// trinoConsoleWiring is the admin console's half of the Trino branch: the
// cell's identity plus a coordinator client authenticated as the OBSERVER
// principal.
//
// The observer is deliberately NOT the provisioner's admin principal. The
// admin can CREATE/DROP catalogs and, by policy, sees only its own queries;
// the observer sees every tenant's query metadata and holds no catalog at
// all. Keeping them separate means a leak of either credential yields one
// half of that authority, never both. See opa.ObserverPrincipal.
type trinoConsoleWiring struct {
	Cell     admin.TrinoCell
	Observer admin.TrinoCoordinatorClient
}

// newTrinoAdminAPI builds the console's Trino surface, or nil when the
// deployment has no cell. Split out so multitenant.go can construct it at
// the point where the audit store finally exists.
func newTrinoAdminAPI(console *trinoConsoleWiring, orgs admin.TrinoOrgStore, audit *admin.AuditStore) *admin.TrinoAPI {
	if console == nil {
		return nil
	}
	return admin.NewTrinoAPI(console.Cell, console.Observer, orgs, audit)
}

// buildTrinoWiring constructs everything the Trino branch needs from
// env vars + the supplied configstore-backed reads. Returns nil when
// the provisioner is disabled (URL not set) and an error when it's
// enabled but the env is incomplete.
//
// The kubernetes.Interface is a typed client suitable for projecting
// Secrets and ConfigMaps into the Trino namespace. In prod the caller
// builds it from rest.InClusterConfig(); in dev/test the caller can pass
// a fake.
//
// ducklings resolves one org's Duckling CR status — the metadata-store
// password plus the object-store inputs a catalog needs. The caller passes
// the SAME Duckling-CR read the worker activation path uses, so there is one
// definition of "the tenant's metadata password" in the control plane, and a
// duckling that has not published a credential yet reads as "wait" on both
// paths.
//
// The cluster-level credentials (Trino internal-communication shared
// secret, admin password + bcrypt hash, OPA bundle bearer token) are
// NOT read from env — they're self-generated by the provisioner with
// the K8s Secret as the source of truth (a one-bit configstore sentinel
// records "ever bootstrapped"). We run that bootstrap SYNCHRONOUSLY
// here (provisioner.Bootstrap) to obtain the bundle bearer token, then
// construct the bundle HTTP handler with the real token directly.
// Because the handler can't be built until the token is known, there's
// no window where /bundles/trino serves with a placeholder — the
// ordering is enforced by construction. The caller can start the API
// server immediately after this returns.
func buildTrinoWiring(
	store *configstore.ConfigStore,
	kc kubernetes.Interface,
	ducklings provisioner.TrinoDucklingResolver,
) (*trinoWiring, error) {
	if !trinoProvisionerEnabled() {
		return nil, nil
	}

	cell, err := resolveTrinoCell()
	if err != nil {
		return nil, err
	}

	if ducklings == nil {
		// Without it every catalog sits pending forever waiting on a
		// duckling status that nothing resolves — a silent, permanent
		// half-provisioned cell. Fail the rollout instead.
		return nil, fmt.Errorf("trino provisioner requires a duckling status resolver (the Duckling CR client is unavailable)")
	}

	// Catalog client with empty credentials — Bootstrap (below) calls
	// SetCredentials with the bootstrapped admin pair before the
	// provisioner issues any catalog REST call. The cell's TLSServerName
	// pins TLS verification to the coordinator cert's hostname when the URL
	// is https but dials the in-cluster Service address (see
	// envTrinoCoordinatorServerName).
	catalogClient := provisioner.NewTrinoCatalogHTTPClient(cell.CoordinatorURL, opa.AdminPrincipal, "", cell.TLSServerName)

	bundleStore := &opa.BundleStore{}

	trinoProv, err := provisioner.NewTrinoProvisioner(provisioner.TrinoProvisionerOpts{
		Store:                 store,
		BootstrapSentinel:     store,
		Warehouses:            store,
		Ducklings:             ducklings,
		Kubernetes:            kc,
		Namespace:             strings.TrimSpace(os.Getenv(envTrinoNamespace)),
		CellID:                cell.ID,
		TenantSecretMountPath: strings.TrimSpace(os.Getenv(envTrinoTenantSecretMountPath)),
		Catalog:               catalogClient,
		BundleStore:           bundleStore,
		BundleBuilder:         opa.NewBuilder(),
		AWSRegion:             strings.TrimSpace(os.Getenv(envTrinoAWSRegion)),
		S3MaxConnections:      envInt(envTrinoS3MaxConnections),
	})
	if err != nil {
		return nil, fmt.Errorf("construct Trino provisioner: %w", err)
	}

	// Synchronous bootstrap: generates (first install) or loads the
	// cluster credentials, seeds the catalog client's admin credential,
	// and returns the OPA bundle bearer token. Bounded by a generous
	// timeout — if Postgres or the K8s API server is unreachable for
	// minutes, that's a hard startup failure surfaced in the pod logs.
	bootstrapCtx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	defer cancel()
	bundleToken, err := trinoProv.Bootstrap(bootstrapCtx)
	if err != nil {
		return nil, fmt.Errorf("bootstrap Trino cluster secrets: %w", err)
	}

	// Build the handler with the real token directly — no placeholder,
	// no post-construction swap, so no window where the endpoint serves
	// with a token a real client could match by accident.
	bundleHandler := opa.NewHandler(bundleStore, opa.BearerTokenAuth(bundleToken))

	return &trinoWiring{
		Provisioner:   trinoProv,
		BundleStore:   bundleStore,
		BundleHandler: bundleHandler,
		Cell:          cell,
		Console: &trinoConsoleWiring{
			Cell: admin.TrinoCell{
				ID:             cell.ID,
				CoordinatorURL: cell.CoordinatorURL,
				TLSServerName:  cell.TLSServerName,
				ClientURL:      cell.ClientURL,
			},
			// Read the credential through the provisioner on every call
			// rather than capturing it here: the pair is regenerated if it
			// ever goes missing, and a captured copy would 401 forever
			// after that self-heal.
			Observer: admin.NewTrinoCoordinatorClient(
				cell.CoordinatorURL, cell.TLSServerName, trinoProv.ObserverCredential),
		},
	}, nil
}

// The provisioner reads a tenant's duckling status through the control
// plane's existing Duckling CR reader, passed in by the caller.
//
// This is deliberately the SAME read the worker activation path performs
// (SharedWorkerActivator.buildDuckLakeConfigFromDuckling reaches the
// password through the same resolver, which resolves
// status.metadataStore.credentialSecretRef into a plaintext) rather than a
// parallel implementation, so Trino and the DuckDB workers can never end up
// authenticating a tenant's metadata store with two different credentials.
//
// A duckling with no status published yet returns (nil, nil) — a WAIT, which
// leaves the org provisioning until the composition catches up. Only a genuine
// read failure is an error.
//
// The provisioner takes the whole status rather than just the password because
// the catalog needs the object-store inputs too — bucket, region and the
// per-org IAM role — and those live ONLY here. The config store's
// ManagedWarehouse carries s3.* and worker_identity.* columns, but nothing
// populates them for a DuckLake warehouse: the bucket lands on
// data_store.bucket_name and the role is a Crossplane composition output
// published to the Duckling CR's status. Reading them from the same status the
// password comes from also keeps Trino and the DuckDB workers pointed at the
// same bucket under the same identity, which is the property that matters.

// envInt reads a non-negative integer env var, returning 0 for unset,
// blank, or unparseable values so the caller's own default applies.
func envInt(name string) int {
	v := strings.TrimSpace(os.Getenv(name))
	if v == "" {
		return 0
	}
	n, err := strconv.Atoi(v)
	if err != nil || n < 0 {
		return 0
	}
	return n
}
