// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: controlplane/proto/worker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataDir       string                 `protobuf:"bytes,1,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	Extensions    []string               `protobuf:"bytes,2,rep,name=extensions,proto3" json:"extensions,omitempty"`
	IdleTimeoutNs int64                  `protobuf:"varint,3,opt,name=idle_timeout_ns,json=idleTimeoutNs,proto3" json:"idle_timeout_ns,omitempty"`
	// TLS configuration
	TlsCertFile string `protobuf:"bytes,4,opt,name=tls_cert_file,json=tlsCertFile,proto3" json:"tls_cert_file,omitempty"`
	TlsKeyFile  string `protobuf:"bytes,5,opt,name=tls_key_file,json=tlsKeyFile,proto3" json:"tls_key_file,omitempty"`
	// DuckLake configuration
	Ducklake *DuckLakeConfig `protobuf:"bytes,6,opt,name=ducklake,proto3" json:"ducklake,omitempty"`
	// Authentication - map of username -> password
	Users         map[string]string `protobuf:"bytes,7,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_controlplane_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigureRequest) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *ConfigureRequest) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *ConfigureRequest) GetIdleTimeoutNs() int64 {
	if x != nil {
		return x.IdleTimeoutNs
	}
	return 0
}

func (x *ConfigureRequest) GetTlsCertFile() string {
	if x != nil {
		return x.TlsCertFile
	}
	return ""
}

func (x *ConfigureRequest) GetTlsKeyFile() string {
	if x != nil {
		return x.TlsKeyFile
	}
	return ""
}

func (x *ConfigureRequest) GetDucklake() *DuckLakeConfig {
	if x != nil {
		return x.Ducklake
	}
	return nil
}

func (x *ConfigureRequest) GetUsers() map[string]string {
	if x != nil {
		return x.Users
	}
	return nil
}

type DuckLakeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetadataStore string                 `protobuf:"bytes,1,opt,name=metadata_store,json=metadataStore,proto3" json:"metadata_store,omitempty"`
	ObjectStore   string                 `protobuf:"bytes,2,opt,name=object_store,json=objectStore,proto3" json:"object_store,omitempty"`
	DataPath      string                 `protobuf:"bytes,3,opt,name=data_path,json=dataPath,proto3" json:"data_path,omitempty"`
	S3Provider    string                 `protobuf:"bytes,4,opt,name=s3_provider,json=s3Provider,proto3" json:"s3_provider,omitempty"`
	S3Endpoint    string                 `protobuf:"bytes,5,opt,name=s3_endpoint,json=s3Endpoint,proto3" json:"s3_endpoint,omitempty"`
	S3AccessKey   string                 `protobuf:"bytes,6,opt,name=s3_access_key,json=s3AccessKey,proto3" json:"s3_access_key,omitempty"`
	S3SecretKey   string                 `protobuf:"bytes,7,opt,name=s3_secret_key,json=s3SecretKey,proto3" json:"s3_secret_key,omitempty"`
	S3Region      string                 `protobuf:"bytes,8,opt,name=s3_region,json=s3Region,proto3" json:"s3_region,omitempty"`
	S3UseSsl      bool                   `protobuf:"varint,9,opt,name=s3_use_ssl,json=s3UseSsl,proto3" json:"s3_use_ssl,omitempty"`
	S3UrlStyle    string                 `protobuf:"bytes,10,opt,name=s3_url_style,json=s3UrlStyle,proto3" json:"s3_url_style,omitempty"`
	S3Chain       string                 `protobuf:"bytes,11,opt,name=s3_chain,json=s3Chain,proto3" json:"s3_chain,omitempty"`
	S3Profile     string                 `protobuf:"bytes,12,opt,name=s3_profile,json=s3Profile,proto3" json:"s3_profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DuckLakeConfig) Reset() {
	*x = DuckLakeConfig{}
	mi := &file_controlplane_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DuckLakeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DuckLakeConfig) ProtoMessage() {}

func (x *DuckLakeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DuckLakeConfig.ProtoReflect.Descriptor instead.
func (*DuckLakeConfig) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *DuckLakeConfig) GetMetadataStore() string {
	if x != nil {
		return x.MetadataStore
	}
	return ""
}

func (x *DuckLakeConfig) GetObjectStore() string {
	if x != nil {
		return x.ObjectStore
	}
	return ""
}

func (x *DuckLakeConfig) GetDataPath() string {
	if x != nil {
		return x.DataPath
	}
	return ""
}

func (x *DuckLakeConfig) GetS3Provider() string {
	if x != nil {
		return x.S3Provider
	}
	return ""
}

func (x *DuckLakeConfig) GetS3Endpoint() string {
	if x != nil {
		return x.S3Endpoint
	}
	return ""
}

func (x *DuckLakeConfig) GetS3AccessKey() string {
	if x != nil {
		return x.S3AccessKey
	}
	return ""
}

func (x *DuckLakeConfig) GetS3SecretKey() string {
	if x != nil {
		return x.S3SecretKey
	}
	return ""
}

func (x *DuckLakeConfig) GetS3Region() string {
	if x != nil {
		return x.S3Region
	}
	return ""
}

func (x *DuckLakeConfig) GetS3UseSsl() bool {
	if x != nil {
		return x.S3UseSsl
	}
	return false
}

func (x *DuckLakeConfig) GetS3UrlStyle() string {
	if x != nil {
		return x.S3UrlStyle
	}
	return ""
}

func (x *DuckLakeConfig) GetS3Chain() string {
	if x != nil {
		return x.S3Chain
	}
	return ""
}

func (x *DuckLakeConfig) GetS3Profile() string {
	if x != nil {
		return x.S3Profile
	}
	return ""
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_controlplane_proto_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_worker_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigureResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ConfigureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AcceptConnectionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RemoteAddr       string                 `protobuf:"bytes,1,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	BackendSecretKey int32                  `protobuf:"varint,2,opt,name=backend_secret_key,json=backendSecretKey,proto3" json:"backend_secret_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AcceptConnectionRequest) Reset() {
	*x = AcceptConnectionRequest{}
	mi := &file_controlplane_proto_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptConnectionRequest) ProtoMessage() {}

func (x *AcceptConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptConnectionRequest.ProtoReflect.Descriptor instead.
func (*AcceptConnectionRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_worker_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptConnectionRequest) GetRemoteAddr() string {
	if x != nil {
		return x.RemoteAddr
	}
	return ""
}

func (x *AcceptConnectionRequest) GetBackendSecretKey() int32 {
	if x != nil {
		return x.BackendSecretKey
	}
	return 0
}

type AcceptConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	BackendPid    int32                  `protobuf:"varint,2,opt,name=backend_pid,json=backendPid,proto3" json:"backend_pid,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptConnectionResponse) Reset() {
	*x = AcceptConnectionResponse{}
	mi := &file_controlplane_proto_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptConnectionResponse) ProtoMessage() {}

func (x *AcceptConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptConnectionResponse.ProtoReflect.Descriptor instead.
func (*AcceptConnectionResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_worker_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptConnectionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AcceptConnectionResponse) GetBackendPid() int32 {
	if x != nil {
		return x.BackendPid
	}
	return 0
}

func (x *AcceptConnectionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CancelQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendPid    int32                  `protobuf:"varint,1,opt,name=backend_pid,json=backendPid,proto3" json:"backend_pid,omitempty"`
	SecretKey     int32                  `protobuf:"varint,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelQueryRequest) Reset() {
	*x = CancelQueryRequest{}
	mi := &file_controlplane_proto_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelQueryRequest) ProtoMessage() {}

func (x *CancelQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelQueryRequest.ProtoReflect.Descriptor instead.
func (*CancelQueryRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_worker_proto_rawDescGZIP(), []int{5}
}

func (x *CancelQueryRequest) GetBackendPid() int32 {
	if x != nil {
		return x.BackendPid
	}
	return 0
}

func (x *CancelQueryRequest) GetSecretKey() int32 {
	if x != nil {
		return x.SecretKey
	}
	return 0
}

type CancelQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelQueryResponse) Reset() {
	*x = CancelQueryResponse{}
	mi := &file_controlplane_proto_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelQueryResponse) ProtoMessage() {}

func (x *CancelQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelQueryResponse.ProtoReflect.Descriptor instead.
func (*CancelQueryResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_worker_proto_rawDescGZIP(), []int{6}
}

func (x *CancelQueryResponse) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

type DrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeoutNs     int64                  `protobuf:"varint,1,opt,name=timeout_ns,json=timeoutNs,proto3" json:"timeout_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_controlplane_proto_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_worker_proto_rawDescGZIP(), []int{7}
}

func (x *DrainRequest) GetTimeoutNs() int64 {
	if x != nil {
		return x.TimeoutNs
	}
	return 0
}

type DrainResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Ok                   bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	RemainingConnections int32                  `protobuf:"varint,2,opt,name=remaining_connections,json=remainingConnections,proto3" json:"remaining_connections,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DrainResponse) Reset() {
	*x = DrainResponse{}
	mi := &file_controlplane_proto_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainResponse) ProtoMessage() {}

func (x *DrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainResponse.ProtoReflect.Descriptor instead.
func (*DrainResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_worker_proto_rawDescGZIP(), []int{8}
}

func (x *DrainResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DrainResponse) GetRemainingConnections() int32 {
	if x != nil {
		return x.RemainingConnections
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_controlplane_proto_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_worker_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Healthy           bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	UptimeNs          int64                  `protobuf:"varint,3,opt,name=uptime_ns,json=uptimeNs,proto3" json:"uptime_ns,omitempty"`
	TotalQueries      int64                  `protobuf:"varint,4,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`
	Draining          bool                   `protobuf:"varint,5,opt,name=draining,proto3" json:"draining,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_controlplane_proto_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_worker_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *HealthResponse) GetUptimeNs() int64 {
	if x != nil {
		return x.UptimeNs
	}
	return 0
}

func (x *HealthResponse) GetTotalQueries() int64 {
	if x != nil {
		return x.TotalQueries
	}
	return 0
}

func (x *HealthResponse) GetDraining() bool {
	if x != nil {
		return x.Draining
	}
	return false
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeoutNs     int64                  `protobuf:"varint,1,opt,name=timeout_ns,json=timeoutNs,proto3" json:"timeout_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_controlplane_proto_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_worker_proto_rawDescGZIP(), []int{11}
}

func (x *ShutdownRequest) GetTimeoutNs() int64 {
	if x != nil {
		return x.TimeoutNs
	}
	return 0
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_controlplane_proto_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_proto_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_proto_worker_proto_rawDescGZIP(), []int{12}
}

func (x *ShutdownResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_controlplane_proto_worker_proto protoreflect.FileDescriptor

const file_controlplane_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x1fcontrolplane/proto/worker.proto\x12\fcontrolplane\"\xf0\x02\n" +
	"\x10ConfigureRequest\x12\x19\n" +
	"\bdata_dir\x18\x01 \x01(\tR\adataDir\x12\x1e\n" +
	"\n" +
	"extensions\x18\x02 \x03(\tR\n" +
	"extensions\x12&\n" +
	"\x0fidle_timeout_ns\x18\x03 \x01(\x03R\ridleTimeoutNs\x12\"\n" +
	"\rtls_cert_file\x18\x04 \x01(\tR\vtlsCertFile\x12 \n" +
	"\ftls_key_file\x18\x05 \x01(\tR\n" +
	"tlsKeyFile\x128\n" +
	"\bducklake\x18\x06 \x01(\v2\x1c.controlplane.DuckLakeConfigR\bducklake\x12?\n" +
	"\x05users\x18\a \x03(\v2).controlplane.ConfigureRequest.UsersEntryR\x05users\x1a8\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x03\n" +
	"\x0eDuckLakeConfig\x12%\n" +
	"\x0emetadata_store\x18\x01 \x01(\tR\rmetadataStore\x12!\n" +
	"\fobject_store\x18\x02 \x01(\tR\vobjectStore\x12\x1b\n" +
	"\tdata_path\x18\x03 \x01(\tR\bdataPath\x12\x1f\n" +
	"\vs3_provider\x18\x04 \x01(\tR\n" +
	"s3Provider\x12\x1f\n" +
	"\vs3_endpoint\x18\x05 \x01(\tR\n" +
	"s3Endpoint\x12\"\n" +
	"\rs3_access_key\x18\x06 \x01(\tR\vs3AccessKey\x12\"\n" +
	"\rs3_secret_key\x18\a \x01(\tR\vs3SecretKey\x12\x1b\n" +
	"\ts3_region\x18\b \x01(\tR\bs3Region\x12\x1c\n" +
	"\n" +
	"s3_use_ssl\x18\t \x01(\bR\bs3UseSsl\x12 \n" +
	"\fs3_url_style\x18\n" +
	" \x01(\tR\n" +
	"s3UrlStyle\x12\x19\n" +
	"\bs3_chain\x18\v \x01(\tR\as3Chain\x12\x1d\n" +
	"\n" +
	"s3_profile\x18\f \x01(\tR\ts3Profile\"9\n" +
	"\x11ConfigureResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"h\n" +
	"\x17AcceptConnectionRequest\x12\x1f\n" +
	"\vremote_addr\x18\x01 \x01(\tR\n" +
	"remoteAddr\x12,\n" +
	"\x12backend_secret_key\x18\x02 \x01(\x05R\x10backendSecretKey\"a\n" +
	"\x18AcceptConnectionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1f\n" +
	"\vbackend_pid\x18\x02 \x01(\x05R\n" +
	"backendPid\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"T\n" +
	"\x12CancelQueryRequest\x12\x1f\n" +
	"\vbackend_pid\x18\x01 \x01(\x05R\n" +
	"backendPid\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\x05R\tsecretKey\"3\n" +
	"\x13CancelQueryResponse\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\"-\n" +
	"\fDrainRequest\x12\x1d\n" +
	"\n" +
	"timeout_ns\x18\x01 \x01(\x03R\ttimeoutNs\"T\n" +
	"\rDrainResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x123\n" +
	"\x15remaining_connections\x18\x02 \x01(\x05R\x14remainingConnections\"\x0f\n" +
	"\rHealthRequest\"\xb7\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x05R\x11activeConnections\x12\x1b\n" +
	"\tuptime_ns\x18\x03 \x01(\x03R\buptimeNs\x12#\n" +
	"\rtotal_queries\x18\x04 \x01(\x03R\ftotalQueries\x12\x1a\n" +
	"\bdraining\x18\x05 \x01(\bR\bdraining\"0\n" +
	"\x0fShutdownRequest\x12\x1d\n" +
	"\n" +
	"timeout_ns\x18\x01 \x01(\x03R\ttimeoutNs\"\"\n" +
	"\x10ShutdownResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xe6\x03\n" +
	"\rWorkerControl\x12L\n" +
	"\tConfigure\x12\x1e.controlplane.ConfigureRequest\x1a\x1f.controlplane.ConfigureResponse\x12a\n" +
	"\x10AcceptConnection\x12%.controlplane.AcceptConnectionRequest\x1a&.controlplane.AcceptConnectionResponse\x12R\n" +
	"\vCancelQuery\x12 .controlplane.CancelQueryRequest\x1a!.controlplane.CancelQueryResponse\x12@\n" +
	"\x05Drain\x12\x1a.controlplane.DrainRequest\x1a\x1b.controlplane.DrainResponse\x12C\n" +
	"\x06Health\x12\x1b.controlplane.HealthRequest\x1a\x1c.controlplane.HealthResponse\x12I\n" +
	"\bShutdown\x12\x1d.controlplane.ShutdownRequest\x1a\x1e.controlplane.ShutdownResponseB0Z.github.com/posthog/duckgres/controlplane/protob\x06proto3"

var (
	file_controlplane_proto_worker_proto_rawDescOnce sync.Once
	file_controlplane_proto_worker_proto_rawDescData []byte
)

func file_controlplane_proto_worker_proto_rawDescGZIP() []byte {
	file_controlplane_proto_worker_proto_rawDescOnce.Do(func() {
		file_controlplane_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_proto_worker_proto_rawDesc), len(file_controlplane_proto_worker_proto_rawDesc)))
	})
	return file_controlplane_proto_worker_proto_rawDescData
}

var file_controlplane_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_controlplane_proto_worker_proto_goTypes = []any{
	(*ConfigureRequest)(nil),         // 0: controlplane.ConfigureRequest
	(*DuckLakeConfig)(nil),           // 1: controlplane.DuckLakeConfig
	(*ConfigureResponse)(nil),        // 2: controlplane.ConfigureResponse
	(*AcceptConnectionRequest)(nil),  // 3: controlplane.AcceptConnectionRequest
	(*AcceptConnectionResponse)(nil), // 4: controlplane.AcceptConnectionResponse
	(*CancelQueryRequest)(nil),       // 5: controlplane.CancelQueryRequest
	(*CancelQueryResponse)(nil),      // 6: controlplane.CancelQueryResponse
	(*DrainRequest)(nil),             // 7: controlplane.DrainRequest
	(*DrainResponse)(nil),            // 8: controlplane.DrainResponse
	(*HealthRequest)(nil),            // 9: controlplane.HealthRequest
	(*HealthResponse)(nil),           // 10: controlplane.HealthResponse
	(*ShutdownRequest)(nil),          // 11: controlplane.ShutdownRequest
	(*ShutdownResponse)(nil),         // 12: controlplane.ShutdownResponse
	nil,                              // 13: controlplane.ConfigureRequest.UsersEntry
}
var file_controlplane_proto_worker_proto_depIdxs = []int32{
	1,  // 0: controlplane.ConfigureRequest.ducklake:type_name -> controlplane.DuckLakeConfig
	13, // 1: controlplane.ConfigureRequest.users:type_name -> controlplane.ConfigureRequest.UsersEntry
	0,  // 2: controlplane.WorkerControl.Configure:input_type -> controlplane.ConfigureRequest
	3,  // 3: controlplane.WorkerControl.AcceptConnection:input_type -> controlplane.AcceptConnectionRequest
	5,  // 4: controlplane.WorkerControl.CancelQuery:input_type -> controlplane.CancelQueryRequest
	7,  // 5: controlplane.WorkerControl.Drain:input_type -> controlplane.DrainRequest
	9,  // 6: controlplane.WorkerControl.Health:input_type -> controlplane.HealthRequest
	11, // 7: controlplane.WorkerControl.Shutdown:input_type -> controlplane.ShutdownRequest
	2,  // 8: controlplane.WorkerControl.Configure:output_type -> controlplane.ConfigureResponse
	4,  // 9: controlplane.WorkerControl.AcceptConnection:output_type -> controlplane.AcceptConnectionResponse
	6,  // 10: controlplane.WorkerControl.CancelQuery:output_type -> controlplane.CancelQueryResponse
	8,  // 11: controlplane.WorkerControl.Drain:output_type -> controlplane.DrainResponse
	10, // 12: controlplane.WorkerControl.Health:output_type -> controlplane.HealthResponse
	12, // 13: controlplane.WorkerControl.Shutdown:output_type -> controlplane.ShutdownResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_controlplane_proto_worker_proto_init() }
func file_controlplane_proto_worker_proto_init() {
	if File_controlplane_proto_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_proto_worker_proto_rawDesc), len(file_controlplane_proto_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_proto_worker_proto_goTypes,
		DependencyIndexes: file_controlplane_proto_worker_proto_depIdxs,
		MessageInfos:      file_controlplane_proto_worker_proto_msgTypes,
	}.Build()
	File_controlplane_proto_worker_proto = out.File
	file_controlplane_proto_worker_proto_goTypes = nil
	file_controlplane_proto_worker_proto_depIdxs = nil
}
