INSERT INTO duckgres_teams (name, max_workers, min_workers, memory_budget, idle_timeout_s, created_at, updated_at)
VALUES ('local', 0, 0, '', 0, NOW(), NOW())
ON CONFLICT (name) DO UPDATE
SET updated_at = NOW();

INSERT INTO duckgres_managed_warehouses (
    team_name,
    aurora_region,
    aurora_endpoint,
    aurora_port,
    aurora_database_name,
    aurora_username,
    s3_provider,
    s3_region,
    s3_bucket,
    s3_path_prefix,
    s3_endpoint,
    s3_use_ssl,
    s3_url_style,
    worker_identity_namespace,
    worker_identity_service_account_name,
    worker_identity_iam_role_arn,
    aurora_credentials_namespace,
    aurora_credentials_name,
    aurora_credentials_key,
    s3_credentials_namespace,
    s3_credentials_name,
    s3_credentials_key,
    runtime_config_namespace,
    runtime_config_name,
    runtime_config_key,
    state,
    status_message,
    aurora_state,
    aurora_status_message,
    s3_state,
    s3_status_message,
    identity_state,
    identity_status_message,
    secrets_state,
    secrets_status_message,
    ready_at,
    failed_at,
    created_at,
    updated_at
)
VALUES (
    'local',
    'local-dev',
    'local-aurora.internal',
    5432,
    'duckgres_local',
    'duckgres',
    'minio',
    'us-east-1',
    'duckgres-local',
    'teams/local/',
    'host.docker.internal:39000',
    false,
    'path',
    'duckgres',
    'duckgres-local-worker',
    'arn:aws:iam::000000000000:role/duckgres-local-worker',
    'duckgres',
    'duckgres-local-aurora',
    'dsn',
    'duckgres',
    'duckgres-local-s3',
    'credentials',
    'duckgres',
    'duckgres-local-runtime',
    'duckgres.yaml',
    'ready',
    'local development warehouse metadata',
    'ready',
    'local aurora metadata seeded',
    'ready',
    'local object store metadata seeded',
    'ready',
    'local worker identity metadata seeded',
    'ready',
    'local secret refs seeded',
    NOW(),
    NULL,
    NOW(),
    NOW()
)
ON CONFLICT (team_name) DO UPDATE
SET aurora_region = EXCLUDED.aurora_region,
    aurora_endpoint = EXCLUDED.aurora_endpoint,
    aurora_port = EXCLUDED.aurora_port,
    aurora_database_name = EXCLUDED.aurora_database_name,
    aurora_username = EXCLUDED.aurora_username,
    s3_provider = EXCLUDED.s3_provider,
    s3_region = EXCLUDED.s3_region,
    s3_bucket = EXCLUDED.s3_bucket,
    s3_path_prefix = EXCLUDED.s3_path_prefix,
    s3_endpoint = EXCLUDED.s3_endpoint,
    s3_use_ssl = EXCLUDED.s3_use_ssl,
    s3_url_style = EXCLUDED.s3_url_style,
    worker_identity_namespace = EXCLUDED.worker_identity_namespace,
    worker_identity_service_account_name = EXCLUDED.worker_identity_service_account_name,
    worker_identity_iam_role_arn = EXCLUDED.worker_identity_iam_role_arn,
    aurora_credentials_namespace = EXCLUDED.aurora_credentials_namespace,
    aurora_credentials_name = EXCLUDED.aurora_credentials_name,
    aurora_credentials_key = EXCLUDED.aurora_credentials_key,
    s3_credentials_namespace = EXCLUDED.s3_credentials_namespace,
    s3_credentials_name = EXCLUDED.s3_credentials_name,
    s3_credentials_key = EXCLUDED.s3_credentials_key,
    runtime_config_namespace = EXCLUDED.runtime_config_namespace,
    runtime_config_name = EXCLUDED.runtime_config_name,
    runtime_config_key = EXCLUDED.runtime_config_key,
    state = EXCLUDED.state,
    status_message = EXCLUDED.status_message,
    aurora_state = EXCLUDED.aurora_state,
    aurora_status_message = EXCLUDED.aurora_status_message,
    s3_state = EXCLUDED.s3_state,
    s3_status_message = EXCLUDED.s3_status_message,
    identity_state = EXCLUDED.identity_state,
    identity_status_message = EXCLUDED.identity_status_message,
    secrets_state = EXCLUDED.secrets_state,
    secrets_status_message = EXCLUDED.secrets_status_message,
    ready_at = EXCLUDED.ready_at,
    failed_at = EXCLUDED.failed_at,
    updated_at = NOW();

INSERT INTO duckgres_team_users (username, password, team_name, created_at, updated_at)
VALUES ('postgres', '$2a$10$TQyt73Vw91Q1d7YcE86EVuhms/0u4qBydMDyVvZYlqDwc3/VtQAbm', 'local', NOW(), NOW())
ON CONFLICT (username) DO UPDATE
SET password = EXCLUDED.password,
    team_name = EXCLUDED.team_name,
    updated_at = NOW();
