INSERT INTO duckgres_orgs (name, database_name, max_workers, created_at, updated_at)
VALUES ('local', 'duckgres', 0, NOW(), NOW())
ON CONFLICT (name) DO UPDATE
SET updated_at = NOW();

-- Every org must have at least one PostHog team (duckgres_org_teams row);
-- team 1 is a placeholder for local dev.
INSERT INTO duckgres_org_teams (org_id, team_id, schema_name, enabled, created_at, updated_at)
VALUES ('local', 1, 'team_1', TRUE, NOW(), NOW())
ON CONFLICT (org_id, team_id) DO UPDATE
SET updated_at = NOW();

INSERT INTO duckgres_managed_warehouses (
    org_id,
    duckling_name,
    warehouse_database_endpoint,
    warehouse_database_port,
    metadata_store_kind,
    metadata_store_endpoint,
    metadata_store_port,
    metadata_store_database_name,
    metadata_store_username,
    s3_provider,
    s3_region,
    s3_bucket,
    s3_path_prefix,
    s3_endpoint,
    s3_use_ssl,
    s3_url_style,
    worker_identity_namespace,
    worker_identity_iam_role_arn,
    warehouse_database_credentials_namespace,
    warehouse_database_credentials_name,
    warehouse_database_credentials_key,
    metadata_store_credentials_namespace,
    metadata_store_credentials_name,
    metadata_store_credentials_key,
    s3_credentials_namespace,
    s3_credentials_name,
    s3_credentials_key,
    runtime_config_namespace,
    runtime_config_name,
    runtime_config_key,
    state,
    status_message,
    metadata_store_state,
    s3_state,
    identity_state,
    secrets_state,
    ready_at,
    failed_at,
    created_at,
    updated_at
)
VALUES (
    'local',
    'local',
    'host.docker.internal',
    35434,
    'dedicated_rds',
    'host.docker.internal',
    35433,
    'ducklake_metadata_local',
    'ducklake',
    'minio',
    'us-east-1',
    'duckgres-local',
    'orgs/local/',
    'host.docker.internal:39000',
    false,
    'path',
    'duckgres',
    'arn:aws:iam::000000000000:role/duckgres-local-worker',
    'duckgres',
    'local-warehouse-db',
    'dsn',
    'duckgres',
    'local-metadata',
    'dsn',
    'duckgres',
    'local-s3',
    'credentials',
    'duckgres',
    'local-runtime',
    'duckgres.yaml',
    'ready',
    'local development warehouse metadata',
    'ready',
    'ready',
    'ready',
    'ready',
    NOW(),
    NULL,
    NOW(),
    NOW()
)
ON CONFLICT (org_id) DO UPDATE
SET warehouse_database_endpoint = EXCLUDED.warehouse_database_endpoint,
    warehouse_database_port = EXCLUDED.warehouse_database_port,
    metadata_store_kind = EXCLUDED.metadata_store_kind,
    metadata_store_endpoint = EXCLUDED.metadata_store_endpoint,
    metadata_store_port = EXCLUDED.metadata_store_port,
    metadata_store_database_name = EXCLUDED.metadata_store_database_name,
    metadata_store_username = EXCLUDED.metadata_store_username,
    s3_provider = EXCLUDED.s3_provider,
    s3_region = EXCLUDED.s3_region,
    s3_bucket = EXCLUDED.s3_bucket,
    s3_path_prefix = EXCLUDED.s3_path_prefix,
    s3_endpoint = EXCLUDED.s3_endpoint,
    s3_use_ssl = EXCLUDED.s3_use_ssl,
    s3_url_style = EXCLUDED.s3_url_style,
    worker_identity_namespace = EXCLUDED.worker_identity_namespace,
    worker_identity_iam_role_arn = EXCLUDED.worker_identity_iam_role_arn,
    warehouse_database_credentials_namespace = EXCLUDED.warehouse_database_credentials_namespace,
    warehouse_database_credentials_name = EXCLUDED.warehouse_database_credentials_name,
    warehouse_database_credentials_key = EXCLUDED.warehouse_database_credentials_key,
    metadata_store_credentials_namespace = EXCLUDED.metadata_store_credentials_namespace,
    metadata_store_credentials_name = EXCLUDED.metadata_store_credentials_name,
    metadata_store_credentials_key = EXCLUDED.metadata_store_credentials_key,
    s3_credentials_namespace = EXCLUDED.s3_credentials_namespace,
    s3_credentials_name = EXCLUDED.s3_credentials_name,
    s3_credentials_key = EXCLUDED.s3_credentials_key,
    runtime_config_namespace = EXCLUDED.runtime_config_namespace,
    runtime_config_name = EXCLUDED.runtime_config_name,
    runtime_config_key = EXCLUDED.runtime_config_key,
    state = EXCLUDED.state,
    status_message = EXCLUDED.status_message,
    metadata_store_state = EXCLUDED.metadata_store_state,
    s3_state = EXCLUDED.s3_state,
    identity_state = EXCLUDED.identity_state,
    secrets_state = EXCLUDED.secrets_state,
    ready_at = EXCLUDED.ready_at,
    failed_at = EXCLUDED.failed_at,
    updated_at = NOW();

INSERT INTO duckgres_org_users (username, password, org_id, created_at, updated_at)
VALUES ('postgres', '$2a$10$TQyt73Vw91Q1d7YcE86EVuhms/0u4qBydMDyVvZYlqDwc3/VtQAbm', 'local', NOW(), NOW())
ON CONFLICT (org_id, username) DO UPDATE
SET password = EXCLUDED.password,
    updated_at = NOW();
