apiVersion: v1
kind: Secret
metadata:
  name: local-warehouse-db
  namespace: duckgres
type: Opaque
stringData:
  dsn: duckgres
---
apiVersion: v1
kind: Secret
metadata:
  name: local-metadata
  namespace: duckgres
type: Opaque
stringData:
  dsn: ducklake
---
apiVersion: v1
kind: Secret
metadata:
  name: local-s3
  namespace: duckgres
type: Opaque
stringData:
  credentials: '{"access_key_id":"minioadmin","secret_access_key":"minioadmin"}'
---
apiVersion: v1
kind: Secret
metadata:
  name: local-runtime
  namespace: duckgres
type: Opaque
stringData:
  duckgres.yaml: |
    host: "0.0.0.0"
    port: 5432
    data_dir: "/data"
    users:
      postgres: "postgres"
    extensions:
      - ducklake
