package server

import "strings"

// queryLogColumn is the single source of truth for one query_log column.
//
// The column set used to be spelled out in five places that had to agree by
// hand: the CREATE TABLE DDL, the partition-repair copy list, the INSERT column
// list, the INSERT argument order, and the DuckLake view's SELECT. Drift
// between any two of them is a silent data bug — a mismatched INSERT list
// writes values into the wrong columns. All five are now generated from
// queryLogColumns below, so adding a column is a one-line diff.
//
// Rules for editing queryLogColumns:
//
//   - APPEND new columns; never reorder or remove one. Existing tenants receive
//     new columns through ALTER TABLE ... ADD COLUMN, which always appends
//     physically, so a fresh CREATE TABLE must produce the same order.
//   - Arg == nil means the column is table-managed: excluded from the INSERT
//     and from the DuckLake view, but still copied by the partition-repair path.
//   - PGType is the full DDL fragment, including any DEFAULT.
type queryLogColumn struct {
	Name   string
	PGType string
	// Arg extracts this column's INSERT value from an entry. Nil for
	// table-managed columns (see above).
	Arg func(QueryLogEntry) any
	// initialOnly marks a column that must never be emitted as an
	// ALTER TABLE ... ADD COLUMN against an existing table. Only the identity
	// column qualifies: it has existed since the first schema, and adding an
	// identity column to a populated partitioned table is a rewrite.
	initialOnly bool
}

// queryLogInitialSchemaColumns is the number of leading queryLogColumns entries
// that belong to the original CREATE TABLE. Everything past it is appended and
// reaches existing tenants through ALTER TABLE ... ADD COLUMN, which means an
// appended column MUST be nullable or carry a DEFAULT — a bare NOT NULL cannot
// be added to a populated table. Enforced by
// TestQueryLogAppendedColumnsAreAddable. Never change this number; only the
// list grows.
const queryLogInitialSchemaColumns = 27

// queryLogColumns is the ordered query_log schema. Append only — see above.
var queryLogColumns = []queryLogColumn{
	{Name: "id", PGType: "BIGINT GENERATED BY DEFAULT AS IDENTITY", initialOnly: true},
	{Name: "event_time", PGType: "TIMESTAMPTZ NOT NULL", Arg: func(e QueryLogEntry) any { return e.EventTime }},
	{Name: "query_duration_ms", PGType: "BIGINT NOT NULL", Arg: func(e QueryLogEntry) any { return e.QueryDurationMs }},
	{Name: "type", PGType: "TEXT NOT NULL", Arg: func(e QueryLogEntry) any { return e.Type }},
	{Name: "query", PGType: "TEXT NOT NULL", Arg: func(e QueryLogEntry) any { return truncateQuery(e.Query) }},
	{Name: "transpiled_query", PGType: "TEXT", Arg: func(e QueryLogEntry) any { return truncateNullableQuery(e.TranspiledQuery) }},
	{Name: "query_kind", PGType: "TEXT", Arg: func(e QueryLogEntry) any { return e.QueryKind }},
	{Name: "normalized_query_hash", PGType: "BIGINT", Arg: func(e QueryLogEntry) any { return e.NormalizedHash }},
	{Name: "result_rows", PGType: "BIGINT", Arg: func(e QueryLogEntry) any { return e.ResultRows }},
	{Name: "written_rows", PGType: "BIGINT", Arg: func(e QueryLogEntry) any { return e.WrittenRows }},
	{Name: "exception_code", PGType: "TEXT", Arg: func(e QueryLogEntry) any { return e.ExceptionCode }},
	{Name: "exception", PGType: "TEXT", Arg: func(e QueryLogEntry) any { return e.Exception }},
	{Name: "user_name", PGType: "TEXT NOT NULL", Arg: func(e QueryLogEntry) any { return e.UserName }},
	{Name: "org_id", PGType: "TEXT", Arg: func(e QueryLogEntry) any { return e.OrgID }},
	{Name: "current_database", PGType: "TEXT", Arg: func(e QueryLogEntry) any { return e.CurrentDatabase }},
	{Name: "client_address", PGType: "TEXT", Arg: func(e QueryLogEntry) any { return e.ClientAddress }},
	{Name: "client_port", PGType: "INTEGER", Arg: func(e QueryLogEntry) any { return e.ClientPort }},
	{Name: "application_name", PGType: "TEXT", Arg: func(e QueryLogEntry) any { return e.ApplicationName }},
	{Name: "pid", PGType: "INTEGER", Arg: func(e QueryLogEntry) any { return e.PID }},
	{Name: "worker_id", PGType: "INTEGER", Arg: func(e QueryLogEntry) any { return e.WorkerID }},
	{Name: "is_transpiled", PGType: "BOOLEAN", Arg: func(e QueryLogEntry) any { return e.IsTranspiled }},
	{Name: "protocol", PGType: "TEXT", Arg: func(e QueryLogEntry) any { return e.Protocol }},
	{Name: "trace_id", PGType: "TEXT", Arg: func(e QueryLogEntry) any { return e.TraceID }},
	{Name: "span_id", PGType: "TEXT", Arg: func(e QueryLogEntry) any { return e.SpanID }},
	{Name: "postgres_scan_ms", PGType: "BIGINT DEFAULT 0", Arg: func(e QueryLogEntry) any { return e.PostgresScanMs }},
	{Name: "cpu_time_s", PGType: "DOUBLE PRECISION DEFAULT 0", Arg: func(e QueryLogEntry) any { return e.CPUTimeSeconds }},
	{Name: "peak_buffer_memory_bytes", PGType: "BIGINT DEFAULT 0", Arg: func(e QueryLogEntry) any { return e.PeakBufferMemoryBytes }},
	// --- appended after the initial schema; reach existing tenants via ALTER TABLE ---
	{Name: "query_id", PGType: "TEXT", Arg: func(e QueryLogEntry) any { return e.QueryID }},
	{Name: "parent_query_id", PGType: "TEXT", Arg: func(e QueryLogEntry) any { return e.ParentQueryID }},
	{Name: "statement_index", PGType: "INTEGER DEFAULT 0", Arg: func(e QueryLogEntry) any { return e.StatementIndex }},
	{Name: "access_kinds", PGType: "TEXT", Arg: func(e QueryLogEntry) any { return e.AccessKinds }},
	{Name: "metadata_complete", PGType: "BOOLEAN", Arg: func(e QueryLogEntry) any { return e.MetadataComplete }},
	{Name: "query_metadata", PGType: "TEXT", Arg: func(e QueryLogEntry) any { return truncateQueryMetadata(e.QueryMetadata) }},
}

// queryLogEntryColumns returns the columns duckgres writes, in INSERT order.
func queryLogEntryColumns() []queryLogColumn {
	entryColumns := make([]queryLogColumn, 0, len(queryLogColumns))
	for _, column := range queryLogColumns {
		if column.Arg != nil {
			entryColumns = append(entryColumns, column)
		}
	}
	return entryColumns
}

// queryLogColumnNames returns the names of every column in the table,
// table-managed ones included. The partition-repair path copies rows by this
// list, so it must cover columns duckgres never writes.
func queryLogColumnNames() []string {
	names := make([]string, 0, len(queryLogColumns))
	for _, column := range queryLogColumns {
		names = append(names, column.Name)
	}
	return names
}

// queryLogEntryColumnNames returns the names of the columns duckgres writes.
// This is also the DuckLake view's column list.
func queryLogEntryColumnNames() []string {
	entryColumns := queryLogEntryColumns()
	names := make([]string, 0, len(entryColumns))
	for _, column := range entryColumns {
		names = append(names, column.Name)
	}
	return names
}

// postgresQueryLogColumns is the comma-separated list of every column, used by
// the partition-repair copy.
var postgresQueryLogColumns = strings.Join(queryLogColumnNames(), ", ")

// queryLogEntryInsertArgs returns one entry's INSERT values in column order.
func queryLogEntryInsertArgs(e QueryLogEntry) []any {
	entryColumns := queryLogEntryColumns()
	args := make([]any, 0, len(entryColumns))
	for _, column := range entryColumns {
		args = append(args, column.Arg(e))
	}
	return args
}
