package server

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/posthog/duckgres/server/ducklake"
)

const postgresQueryLogTable = "querylog.query_log_entries"

// NewPostgresQueryLoggerContext creates a worker-local query-log sink backed by
// the tenant metadata Postgres database. The caller owns query-log routing; this
// sink only owns a small native pgx pool and batched append-only inserts.
func NewPostgresQueryLoggerContext(ctx context.Context, dlCfg DuckLakeConfig, cfg QueryLogConfig) (*QueryLogger, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	if !cfg.Enabled {
		return nil, nil
	}
	connStr, err := postgresQueryLogDSN(dlCfg)
	if err != nil {
		return nil, err
	}
	db, err := openPostgresQueryLogDB(connStr)
	if err != nil {
		return nil, err
	}

	if err := ensurePostgresQueryLogTableContext(ctx, db); err != nil {
		_ = db.Close()
		return nil, err
	}

	loggerCtx, cancel := context.WithCancel(context.Background())
	ql := &QueryLogger{
		db:      db,
		cfg:     cfg,
		table:   postgresQueryLogTable,
		ch:      make(chan QueryLogEntry, queryLogChannelSize),
		done:    make(chan struct{}),
		ctx:     loggerCtx,
		cancel:  cancel,
		closeDB: true,
	}
	go ql.flushLoop()
	return ql, nil
}

func openPostgresQueryLogDB(connStr string) (*sql.DB, error) {
	db, err := sql.Open("pgx", connStr)
	if err != nil {
		return nil, fmt.Errorf("querylog: open postgres: %w", err)
	}
	db.SetMaxOpenConns(1)
	db.SetMaxIdleConns(1)
	return db, nil
}

func postgresQueryLogDSN(dlCfg DuckLakeConfig) (string, error) {
	connStr, err := ducklake.PostgresMetadataStoreConnString(dlCfg.MetadataStore, dlCfg.ApplicationName)
	if err != nil {
		return "", fmt.Errorf("querylog: %w", err)
	}
	return connStr, nil
}

func ensurePostgresQueryLogTableContext(ctx context.Context, db *sql.DB) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if db == nil {
		return errors.New("querylog: postgres db is nil")
	}
	for _, stmt := range postgresQueryLogSchemaSQL() {
		if _, err := db.ExecContext(ctx, stmt); err != nil {
			return fmt.Errorf("querylog: ensure postgres storage: %w", err)
		}
	}
	return nil
}

func postgresQueryLogSchemaSQL() []string {
	return postgresQueryLogSchemaSQLForTime(time.Now().UTC())
}

func postgresQueryLogSchemaSQLForTime(now time.Time) []string {
	stmts := []string{
		`CREATE SCHEMA IF NOT EXISTS querylog`,
		postgresQueryLogCreateTableSQL(),
	}
	stmts = append(stmts, postgresQueryLogMonthPartitionSQL(now)...)
	stmts = append(stmts,
		`CREATE TABLE IF NOT EXISTS querylog.query_log_entries_default PARTITION OF querylog.query_log_entries DEFAULT`,
		`CREATE INDEX IF NOT EXISTS idx_query_log_entries_event_time ON querylog.query_log_entries (event_time DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_query_log_entries_user_time ON querylog.query_log_entries (user_name, event_time DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_query_log_entries_hash_time ON querylog.query_log_entries (normalized_query_hash, event_time DESC)`,
	)
	return stmts
}

func postgresQueryLogMonthPartitionSQL(now time.Time) []string {
	monthStart := time.Date(now.UTC().Year(), now.UTC().Month(), 1, 0, 0, 0, 0, time.UTC)
	stmts := make([]string, 0, 3)
	for _, monthOffset := range []int{-1, 0, 1} {
		start := monthStart.AddDate(0, monthOffset, 0)
		end := start.AddDate(0, 1, 0)
		name := fmt.Sprintf("querylog.query_log_entries_%04d%02d", start.Year(), int(start.Month()))
		stmts = append(stmts, fmt.Sprintf(
			"CREATE TABLE IF NOT EXISTS %s PARTITION OF querylog.query_log_entries FOR VALUES FROM ('%s') TO ('%s')",
			name,
			start.Format("2006-01-02"),
			end.Format("2006-01-02"),
		))
	}
	return stmts
}

func postgresQueryLogCreateTableSQL() string {
	return `CREATE TABLE IF NOT EXISTS querylog.query_log_entries (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	event_time TIMESTAMPTZ NOT NULL,
	query_duration_ms BIGINT NOT NULL,
	type TEXT NOT NULL,
	query TEXT NOT NULL,
	transpiled_query TEXT,
	query_kind TEXT,
	normalized_query_hash BIGINT,
	result_rows BIGINT,
	written_rows BIGINT,
	exception_code TEXT,
	exception TEXT,
	user_name TEXT NOT NULL,
	org_id TEXT,
	current_database TEXT,
	client_address TEXT,
	client_port INTEGER,
	application_name TEXT,
	pid INTEGER,
	worker_id INTEGER,
	is_transpiled BOOLEAN,
	protocol TEXT,
	trace_id TEXT,
	span_id TEXT,
	postgres_scan_ms BIGINT DEFAULT 0,
	cpu_time_s DOUBLE PRECISION DEFAULT 0,
	peak_buffer_memory_bytes BIGINT DEFAULT 0
) PARTITION BY RANGE (event_time)`
}
