INSERT INTO duckgres_orgs (name, max_workers, memory_budget, idle_timeout_s, created_at, updated_at)
VALUES ('local', 0, '', 0, NOW(), NOW())
ON CONFLICT (name) DO UPDATE
SET updated_at = NOW();

INSERT INTO duckgres_managed_warehouses (
    org_id,
    image,
    aurora_min_acu,
    aurora_max_acu,
    warehouse_database_region,
    warehouse_database_endpoint,
    warehouse_database_port,
    warehouse_database_database_name,
    warehouse_database_username,
    metadata_store_kind,
    metadata_store_engine,
    metadata_store_region,
    metadata_store_endpoint,
    metadata_store_port,
    metadata_store_database_name,
    metadata_store_username,
    s3_provider,
    s3_region,
    s3_bucket,
    s3_path_prefix,
    s3_endpoint,
    s3_use_ssl,
    s3_url_style,
    worker_identity_namespace,
    worker_identity_service_account_name,
    worker_identity_iam_role_arn,
    warehouse_database_credentials_namespace,
    warehouse_database_credentials_name,
    warehouse_database_credentials_key,
    metadata_store_credentials_namespace,
    metadata_store_credentials_name,
    metadata_store_credentials_key,
    s3_credentials_namespace,
    s3_credentials_name,
    s3_credentials_key,
    runtime_config_namespace,
    runtime_config_name,
    runtime_config_key,
    state,
    status_message,
    warehouse_database_state,
    warehouse_database_status_message,
    metadata_store_state,
    metadata_store_status_message,
    s3_state,
    s3_status_message,
    identity_state,
    identity_status_message,
    secrets_state,
    secrets_status_message,
    ready_at,
    failed_at,
    created_at,
    updated_at
)
VALUES (
    'local',
    '',
    0,
    0,
    'kind-dev',
    'duckgres-local-warehouse-db',
    5432,
    'duckgres_local',
    'duckgres',
    'dedicated_rds',
    'postgres',
    'kind-dev',
    'duckgres-local-ducklake-metadata',
    5432,
    'ducklake_metadata_local',
    'ducklake',
    'minio',
    'us-east-1',
    'duckgres-local',
    'orgs/local/',
    'duckgres-local-minio:9000',
    false,
    'path',
    'duckgres',
    'duckgres-local-worker',
    'arn:aws:iam::000000000000:role/duckgres-local-worker',
    'duckgres',
    'duckgres-local-warehouse-db',
    'dsn',
    'duckgres',
    'duckgres-local-metadata',
    'dsn',
    'duckgres',
    'duckgres-local-s3',
    'credentials',
    'duckgres',
    'duckgres-local-runtime',
    'duckgres.yaml',
    'ready',
    'kind local warehouse metadata',
    'ready',
    'kind local warehouse db metadata seeded',
    'ready',
    'kind local metadata store seeded',
    'ready',
    'kind local object store metadata seeded',
    'ready',
    'kind local worker identity metadata seeded',
    'ready',
    'kind local secret refs seeded',
    NOW(),
    NULL,
    NOW(),
    NOW()
)
ON CONFLICT (org_id) DO UPDATE
SET warehouse_database_region = EXCLUDED.warehouse_database_region,
    warehouse_database_endpoint = EXCLUDED.warehouse_database_endpoint,
    warehouse_database_port = EXCLUDED.warehouse_database_port,
    warehouse_database_database_name = EXCLUDED.warehouse_database_database_name,
    warehouse_database_username = EXCLUDED.warehouse_database_username,
    metadata_store_kind = EXCLUDED.metadata_store_kind,
    metadata_store_engine = EXCLUDED.metadata_store_engine,
    metadata_store_region = EXCLUDED.metadata_store_region,
    metadata_store_endpoint = EXCLUDED.metadata_store_endpoint,
    metadata_store_port = EXCLUDED.metadata_store_port,
    metadata_store_database_name = EXCLUDED.metadata_store_database_name,
    metadata_store_username = EXCLUDED.metadata_store_username,
    s3_provider = EXCLUDED.s3_provider,
    s3_region = EXCLUDED.s3_region,
    s3_bucket = EXCLUDED.s3_bucket,
    s3_path_prefix = EXCLUDED.s3_path_prefix,
    s3_endpoint = EXCLUDED.s3_endpoint,
    s3_use_ssl = EXCLUDED.s3_use_ssl,
    s3_url_style = EXCLUDED.s3_url_style,
    worker_identity_namespace = EXCLUDED.worker_identity_namespace,
    worker_identity_service_account_name = EXCLUDED.worker_identity_service_account_name,
    worker_identity_iam_role_arn = EXCLUDED.worker_identity_iam_role_arn,
    warehouse_database_credentials_namespace = EXCLUDED.warehouse_database_credentials_namespace,
    warehouse_database_credentials_name = EXCLUDED.warehouse_database_credentials_name,
    warehouse_database_credentials_key = EXCLUDED.warehouse_database_credentials_key,
    metadata_store_credentials_namespace = EXCLUDED.metadata_store_credentials_namespace,
    metadata_store_credentials_name = EXCLUDED.metadata_store_credentials_name,
    metadata_store_credentials_key = EXCLUDED.metadata_store_credentials_key,
    s3_credentials_namespace = EXCLUDED.s3_credentials_namespace,
    s3_credentials_name = EXCLUDED.s3_credentials_name,
    s3_credentials_key = EXCLUDED.s3_credentials_key,
    runtime_config_namespace = EXCLUDED.runtime_config_namespace,
    runtime_config_name = EXCLUDED.runtime_config_name,
    runtime_config_key = EXCLUDED.runtime_config_key,
    state = EXCLUDED.state,
    status_message = EXCLUDED.status_message,
    warehouse_database_state = EXCLUDED.warehouse_database_state,
    warehouse_database_status_message = EXCLUDED.warehouse_database_status_message,
    metadata_store_state = EXCLUDED.metadata_store_state,
    metadata_store_status_message = EXCLUDED.metadata_store_status_message,
    s3_state = EXCLUDED.s3_state,
    s3_status_message = EXCLUDED.s3_status_message,
    identity_state = EXCLUDED.identity_state,
    identity_status_message = EXCLUDED.identity_status_message,
    secrets_state = EXCLUDED.secrets_state,
    secrets_status_message = EXCLUDED.secrets_status_message,
    ready_at = EXCLUDED.ready_at,
    failed_at = EXCLUDED.failed_at,
    updated_at = NOW();

INSERT INTO duckgres_org_users (username, password, org_id, created_at, updated_at)
VALUES ('postgres', '$2a$10$TQyt73Vw91Q1d7YcE86EVuhms/0u4qBydMDyVvZYlqDwc3/VtQAbm', 'local', NOW(), NOW())
ON CONFLICT (org_id, username) DO UPDATE
SET password = EXCLUDED.password,
    updated_at = NOW();
